# Generated by Django 2.2.3 on 2019-11-07 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maestranza', '0002_auto_20191107_1901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='destinatario',
            new_name='empresa',
        ),
    ]
