# Generated by Django 2.2.6 on 2019-11-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestranza', '0003_auto_20191107_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='persona',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='persona',
            field=models.ManyToManyField(blank=True, to='maestranza.Persona'),
        ),
    ]
