# Generated by Django 2.2.3 on 2020-01-15 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestranza', '0006_auto_20200115_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='prioridad',
            field=models.IntegerField(choices=[(0, 'Baja'), (1, 'Media'), (2, 'Alta')], default=0),
        ),
    ]
