# Generated by Django 2.2.3 on 2020-01-16 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestranza', '0007_proyecto_prioridad'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(choices=[(0, 'Baja'), (1, 'Media'), (2, 'Alta')], default='0')),
            ],
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.IntegerField(choices=[(0, 'Diseno'), (1, 'Materiales'), (2, 'Taller'), (3, 'Cnc'), (4, 'CorteHilo'), (5, 'Torno')], default=0),
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='prioridad',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='prioridad',
            field=models.ManyToManyField(blank=True, to='maestranza.EstadoProyecto'),
        ),
    ]
