# Generated by Django 2.2.3 on 2020-01-16 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestranza', '0008_auto_20200116_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadoproyecto',
            name='priority',
            field=models.IntegerField(choices=[(0, 'Diseno'), (1, 'Materiales'), (2, 'Taller'), (3, 'Cnc'), (4, 'CorteHilo'), (5, 'Torno')], default='0'),
        ),
    ]
