# Generated by Django 2.2.3 on 2020-01-16 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestranza', '0009_auto_20200116_0302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estadoproyecto',
            old_name='priority',
            new_name='estados',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='estado',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='estado',
            field=models.ManyToManyField(blank=True, to='maestranza.EstadoProyecto'),
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='prioridad',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='prioridad',
            field=models.IntegerField(choices=[(0, 'Baja'), (1, 'Media'), (2, 'Alta')], default=0),
        ),
    ]
