# Generated by Django 2.2.3 on 2020-01-16 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maestranza', '0010_auto_20200116_0304'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EstadoProyecto',
            new_name='Estado',
        ),
    ]
