# Generated by Django 2.2.3 on 2020-01-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestranza', '0011_auto_20200116_0308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estado',
            name='estados',
        ),
        migrations.AddField(
            model_name='estado',
            name='estado',
            field=models.CharField(choices=[('Diseno', 0), ('Materiales', 1), ('Taller', 2), ('Cnc', 3), ('CorteHilo', 4), ('Torno', 5)], default='Diseno', max_length=100, verbose_name='estado'),
        ),
    ]
