# Generated by Django 2.2.3 on 2020-01-16 18:59

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('maestranza', '0014_auto_20200116_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='estado',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Diseno', 'diseno'), ('Materiales', 'Materiales'), ('Taller', 'Taller'), ('Cnc', 'Cnc'), ('CorteHilo', 'CorteHilo'), ('Torno', 'Torno')], max_length=44),
        ),
    ]
