# Generated by Django 2.2.3 on 2020-01-16 23:19

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('maestranza', '0015_auto_20200116_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='estado',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='estado',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Diseno', 'diseno'), ('Materiales', 'Materiales'), ('Taller', 'Taller'), ('Cnc', 'Cnc'), ('CorteHilo', 'CorteHilo'), ('Torno', 'Torno')], max_length=44),
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
    ]
