# Generated by Django 2.2.3 on 2020-01-17 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestranza', '0017_auto_20200116_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Diseno', 'diseno'), ('Materiales', 'Materiales'), ('Taller', 'Taller'), ('Cnc', 'Cnc'), ('CorteHilo', 'CorteHilo'), ('Torno', 'Torno')], default='Diseno', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='proyecto',
            name='estados',
            field=models.ManyToManyField(blank=True, to='maestranza.Estados'),
        ),
    ]
