# Generated by Django 2.2.3 on 2020-01-17 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestranza', '0018_auto_20200116_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('Diseno', 'diseno'), ('Materiales', 'Materiales'), ('Taller', 'Taller'), ('Cnc', 'Cnc'), ('CorteHilo', 'CorteHilo'), ('Torno', 'Torno')], max_length=100),
        ),
    ]
